---
title: Hospital Stay Models
author: 
  - name: Adam Gilbert
    email: a.gilbert1@snhu.edu
    affiliations: 
      - name: Southern New Hampshire University
format: html
date: 2/24/2025
date-modified: today
date-format: long
theme: flatly
toc: true
code-fold: true
---

```{r}
#| label: setup
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)

unregister <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}

data <- read_csv("https://raw.githubusercontent.com/agmath/agmath.github.io/master/data/classification/hospital_stays_small.csv")

names(data) <- janitor::make_clean_names(names(data))

set.seed(123)
data_splits <- initial_split(data, strata = stay)
train <- training(data_splits)
test <- testing(data_splits)

train_folds <- vfold_cv(train, v = 10, strata = stay)


```

```{r}
knn_spec <- nearest_neighbor() %>%
  set_engine("kknn") %>%
  set_mode("classification")

knn_rec <- recipe(stay ~ ., data = train) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_rm(all_nominal_predictors()) %>%
  step_rm(case_id) %>%
  step_impute_median(all_numeric_predictors())

knn_wf <- workflow() %>%
  add_model(knn_spec)%>%
  add_recipe(knn_rec)
```


```{r}
tictoc:: tic()

knn_cv_results <- knn_wf %>%
  fit_resamples(
    resamples = train_folds,
    metrics = metric_set(accuracy, mn_log_loss)
  )

tictoc:: toc()
```

```{r}
n_cores <- parallel::detectCores()
cl <- parallel::makeCluster(n_cores - 1, type = "PSOCK")
tictoc:: tic()
doParallel::registerDoParallel(cl)

knn_cv_results <- knn_wf %>%
  fit_resamples(
    resamples = train_folds,
    metrics = metric_set(accuracy, mn_log_loss)
  )

tictoc:: toc()
doParallel::stopImplicitCluster()
unregister()

knn_cv_results %>%
  collect_metrics()

train %>%
  count(stay)
1/11

```